server:
  port: 0

spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    url: jdbc:mariadb://localhost:3306/mentoree_member?characterEncoding=UTF-8&serverTimezone=UTC
    username: mentoreeAdmin
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug

whois:
  api:
    key: F1tJ5ys%2FUMSFiJnpiEcdSCii0XFRSF0GSiqYwMSjJwZdhaKopbZdsZ3etiVgFMq%2BBKzpoA3%2FTkOe8o2cTebjtA%3D%3D
    uri: 'http://apis.data.go.kr/B551505/whois/'

