# Reply
server:
  port: 0

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mentoree_reply?characterEncoding=UTF-8&serverTimezone=UTC
    username: mentoreeAdmin
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug